# # a base docker image is always necessary
FROM ubuntu

# # print "Docker practice"
# RUN echo "Docker practice"

# # the CMD command is used to run an operation in a docker container whereas a RUN command is used to build the image itself
# CMD [ "echo", "Docker learning" ]

# # ENTRYPOINT command is used to overwrite the CMD command function or to execute the specified command before ENTRYPOINT
# # EXAMPLE:
# CMD [ "entrypoint example" ]
# # this would  be executed first and then the CMD command
# ENTRYPOINT [ "echo" ]

# # ADD and COPY commands are pretty much the same

# # ENV command allows to setup environment variables in the container

# ENV SERVER_WORKS=4

# # WORKDIR directive is used to set where the command defined with CMD is to be executed

# # EXPOSE command is sued to associate a specified port to enable networking between the running process inside the container and the outside world

# # MAINTAINER command declares the author hence setting the author field of the images, it should come immediately after FROM

# # VOLUME command is used to enable access from your container to a directory on the host machine (i.e. mounting it)

# VOLUME [ "/data", "/data2" ]