version: '3.1'  # if no version is specified then v1 is assumed. Recommend v2 minimum

# docker container run --detach --env POSTGRES_PASSWORD=password --publish 8080:80 --name psql -v psql-data:/var/lib/postgresql/data postgresql:9

services:
  postgres:
    container_name: psql
    image: postgres
    ports:
      - 8080:80
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - psql-data:/var/lib/postgresql/data
    
volumes:
  psql-data:


